#!/bin/sh

mkdir $WORKSPACE/builds
cd $WORKSPACE/builds
mkdir -p $WORKSPACE/builds/I
mkdir -p $WORKSPACE/builds/transfer/files/testUpdates-I
rm -f $WORKSPACE/builds/transfer/files/testUpdates-I/build_done.txt
$WORKSPACE/org.eclipse.releng.eclipsebuilder/bootstrapHudsone4.sh -test -skipTest -sign -buildDirectory $WORKSPACE/builds/I -hudson -updateSite $WORKSPACE/builds/transfer/files/testUpdates-I I
touch $WORKSPACE/builds/transfer/files/testUpdates-I/build_done.txt
