#!/bin/sh

mkdir $WORKSPACE/builds
cd $WORKSPACE/builds
mkdir -p $WORKSPACE/builds/M
mkdir -p $WORKSPACE/builds/transfer/files/testUpdates-M
$WORKSPACE/org.eclipse.releng.eclipsebuilder/bootstrapHudsongitM.sh -skipTest -buildDirectory $WORKSPACE/builds/M -hudson -updateSite $WORKSPACE/builds/transfer/files/testUpdates-M M