#!/bin/sh

mkdir $WORKSPACE/builds
cd $WORKSPACE/builds
mkdir -p $WORKSPACE/builds/I
mkdir -p $WORKSPACE/builds/transfer/files/testUpdates-M
$WORKSPACE/org.eclipse.releng.eclipsebuilder/bootstrapHudsonM.sh -test -skipTest -buildDirectory $WORKSPACE/builds/M -hudson -sign -updateSite $WORKSPACE/builds/transfer/files/testUpdates-M M