#!/bin/sh

mkdir $WORKSPACE/builds
cd $WORKSPACE/builds
mkdir -p $WORKSPACE/$BUILD_ID/builds/N
mkdir -p $WORKSPACE/$BUILD_ID/builds/transfer/files/testUpdates-N
$WORKSPACE/$BUILD_ID/bootstrapHudson.sh -test -skipTest -buildDirectory $WORKSPACE/$BUILD_ID/builds/N -skipRSS -hudson -skipPack -updateSite $WORKSPACE/builds/transfer/files/testUpdates-N N