#! /bin/sh

#array of zipfiles
zipfiles=`ls *.zip`

for zipfile in ${zipfiles}
do 
	echo [md5] ${zipfile}
	md5sum -b ${zipfile} > checksum/${zipfile}.md5
done

#array of tar.gzip files
gzipfiles=`ls *.gz`

for gzipfile in ${gzipfiles}
do 
	echo [md5] ${gzipfile}
	md5sum -b ${gzipfile} > checksum/${gzipfile}.md5
done

#array of tar.gzip files
gzipfiles=`ls *.gz`

#array of .jar files
jarfiles=`ls *.jar`

for jarfile in ${jarfiles}
do 
	echo [md5] ${jarfile}
	md5sum -b ${jarfile} > checksum/${jarfile}.md5
done